/// <reference types = "Cypress" />

describe("createConsultantManager", function() {

    it("Create new account", function() {

        cy.visit("https://benchy.se/auth/welcome")

        const manName   =   Math.floor(Math.random() * 1000000) + 100000
        // Returns a random integer from 1 to 999999:
        const orgNum    =   manName
        const fullName  =   "auto1"
        const email     =   manName + "@gmail.com"
        const pwd       =   "auto"
        const address1  =   "auto"
        const address2  =   "auto"
        const city      =   "auto"
        const zip       =   "auto"
        const country   =   "auto"

        //start page select ConsultantManager and proceed
        cy.get('.css-twaf9d > :nth-child(3)').click()
        cy.get('.css-78jar2 > .MuiButton-root').click()

        //fill in the form using consts above
        cy.get('#manager_name').type(manName)
        cy.get('#org_number').type(orgNum)
        cy.get('#name').type(fullName)
        cy.get('#email').type(email)
        cy.get('#confirmEmail').type(email)
        cy.get('#password').type(pwd)
        cy.get('#confirmPassword').type(pwd)
        cy.get('#address_line').type(address1)
        cy.get('#address_line_2').type(address2)
        cy.get('#city').type(city)
        cy.get('#zip_code').type(zip)
        cy.get('#country').type(country)
        
        cy.get('.PrivateSwitchBase-input').check()

        //proceed to create account
        cy.get('.MuiButtonBase-root.MuiButton-root.MuiButton-contained').click()

        //upload pictures
        cy.get('.css-v6yg99 > .MuiButton-contained').selectFile('cypress/fixtures/pictures/profilePic.png')
        cy.get('.css-7vl27o > .MuiButton-contained').selectFile('cypress/fixtures/pictures/coverPic.png')

        //fill in some description and complete profile
        cy.get('#manager_description').type("This is an autogenerated test profile")
        cy.get('.css-1eerxkg > .MuiButton-contained').click()

    })
})